version: '3'

services:
  book-scraper:
    build: .
    hostname: book-scraper
    environment:
      FLASK_APP: run.py
      FLASK_DEBUG: 1
    ports:
      - "5000:5000"
    volumes: [".:/app"]
    entrypoint:
      - flask
      - run
      - --host=0.0.0.0



