version: '3'

services:
  app:
    build: .
    hostname: book-scraper
    environment:
      FLASK_APP: run.py
    ports:
      - "5000:5000"
    entrypoint:
      - flask
      - run
      - --host=0.0.0.0