version: '3'

volumes:
  web_data:

services:
  book-scraper:
    build: .
    hostname: book-scraper
    environment:
      FLASK_APP: app
    ports:
      - "5000:5000"
    entrypoint:
      - flask
      - run
      - --host=0.0.0.0
    volumes:
      - web_data:/Users/stach/PycharmProjects/book-scraper/app